version: "2"
#volumes:
#  jenkins-master:
#    driver: "local"
#  jenkins-slave:
#    driver: "local"
services:
  jenkins:
    #image: "blacklabelops/jenkins:2.46.3"
    build: .
    environment:
      - SWARM_JENKINS_USER=lolo
      - SWARM_JENKINS_PASSWORD=lili
      - JENKINS_PLUGINS="swarm"
    ports:
      - "49001:8080"
    restart: "always"
    volumes:
      - "./volumes/master:/jenkins"
    container_name: jenkins1
  jenkins-slave:
    image: "blacklabelops/jenkins-swarm:2.2"
    restart: "always"
    depends_on:
      - jenkins
    links:
    - jenkins
    volumes:
      - "./volumes/slave:/opt/jenkins"
    environment:
      - SWARM_JENKINS_USER=lolo
      - SWARM_JENKINS_PASSWORD=lili
      - SWARM_CLIENT_PARAMETERS=-name 'slave1'
